name: instrument_setting
channels:
  - bioconda
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - altair=5.0.1
  - attrs=24.3.0
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.3.1
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.4
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.1
  - freetype=2.12.1
  - fsspec=2024.12.0
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - greenlet=3.1.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - hdf5=1.14.5
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - kernel-headers_linux-64=3.10.0
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.11.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - libxslt=1.1.41
  - lightning=2.5.0.post0
  - lightning-utilities=0.11.9
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mono=6.12.0.90
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mysql=8.4.0
  - ncurses=6.4
  - nettle=3.7.3
  - numexpr=2.10.1
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.3
  - pcre=8.45
  - pcre2=10.42
  - pillow=11.0.0
  - pip=24.2
  - ply=3.11
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.5.0.post0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rpds-py=0.22.3
  - scikit-learn=1.5.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - spectrum_utils=0.3.2
  - sqlalchemy=2.0.37
  - sqlite=3.45.3
  - swig=4.0.2
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - toolz=1.0.0
  - torchmetrics=1.6.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - azure-core==1.35.1
      - azure-storage-blob==12.26.0
      - azure-storage-file-datalake==12.21.0
      - boto3==1.40.36
      - botocore==1.40.36
      - cachetools==5.5.2
      - cffi==2.0.0
      - click==8.1.8
      - cloudpathlib==0.20.0
      - cloudpickle==3.1.1
      - configspace==1.2.1
      - cryptography==46.0.1
      - cycler==0.12.1
      - dask==2025.1.0
      - dask-jobqueue==0.9.0
      - deprecated==1.2.18
      - deprecation==2.1.0
      - depthcharge-ms==0.4.8
      - dill==0.3.9
      - distributed==2025.1.0
      - einops==0.8.0
      - emcee==3.1.6
      - fastobo==0.12.3
      - fonttools==4.55.3
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.4.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - h5py==3.13.0
      - importlib-metadata==8.6.1
      - isodate==0.7.2
      - jmespath==1.0.1
      - kiwisolver==1.4.8
      - lancedb==0.21.2
      - lark==1.2.2
      - llvmlite==0.44.0
      - locket==1.0.0
      - lxml==5.4.0
      - matchms==0.30.2
      - more-itertools==10.6.0
      - ms-entropy==1.3.9
      - msgpack==1.1.0
      - networkx==3.5
      - numba==0.61.2
      - numpy==2.2.6
      - overrides==7.7.0
      - partd==1.4.2
      - pickydict==0.5.0
      - polars==1.19.0
      - ppx==1.5.0
      - proto-plus==1.26.1
      - protobuf==6.32.1
      - psims==1.3.4
      - psutil==6.1.1
      - pubchempy==1.0.5
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pylance==0.22.0
      - pynisher==1.0.10
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyrfr==0.9.0
      - pyteomics==4.7.5
      - rdkit==2024.9.6
      - regex==2024.11.6
      - rsa==4.9.1
      - s3transfer==0.14.0
      - scipy==1.16.2
      - seaborn==0.13.2
      - selfies==2.1.2
      - sortedcontainers==2.4.0
      - sparsestack==0.7.0
      - spectrum-utils==0.4.2
      - sympy==1.13.1
      - tblib==3.0.0
      - torch-summary==1.4.5
      - typing-inspection==0.4.0
      - wrapt==1.17.3
      - zict==3.0.0
      - zipp==3.21.0
